//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeyHouseEntities : DbContext
    {
        public KeyHouseEntities()
            : base("name=KeyHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipement> Equipement { get; set; }
        public virtual DbSet<ImageLogement> ImageLogement { get; set; }
        public virtual DbSet<Logements> Logements { get; set; }
        public virtual DbSet<RoleUser> RoleUser { get; set; }
        public virtual DbSet<Uitilsateur> Uitilsateur { get; set; }
        public virtual DbSet<villes> villes { get; set; }
    }
}
