//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Logements()
        {
            this.Equipement = new HashSet<Equipement>();
            this.ImageLogement = new HashSet<ImageLogement>();
        }
    
        public int idLogement { get; set; }
        public string TitreLogemenet { get; set; }
        public string DescriptionLogement { get; set; }
        public Nullable<int> Nbrchambre { get; set; }
        public Nullable<decimal> surface { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> idville { get; set; }
        public Nullable<int> IDutilisateur { get; set; }
        public string Typelogement { get; set; }
        public string Adresse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipement> Equipement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageLogement> ImageLogement { get; set; }
        public virtual Uitilsateur Uitilsateur { get; set; }
        public virtual villes villes { get; set; }
    }
}
